### ISSUE TITLE
Composing CSS Modules Results in Duplicate Output

### ISSUE THREAD

**Issue by mgreystone** [faceyspacey/extract-css-chunks-webpack-plugin#55]
I am working with CSS modules & dynamic imports. When importing a CSS file that composes from another module, that code will be duplicated between different modules.

For example:

**app.css**
```css
:global(body) {
  white-space: pre;
}

.base {
  background: #0c0;
}
```

**a.css**
```css
.a {
  composes: base from './app.css';
  color: #aaa;
}
```

**b.css**
```css
.b {
  composes: base from './app.css';
  color: #bbb;
}
```

Builds to

**main.bundle.css**
```css
body {
  white-space: pre;
}

.app__base--DHCDZ {
  background: #0c0;
}
```

**a.bundle.css**
```css
body {
  white-space: pre;
}

.app__base--DHCDZ {
  background: #0c0;
}
.a__a--3qLxd {
  color: #aaa;
}
```

**b.bundle.css**
```css
body {
  white-space: pre;
}

.app__base--DHCDZ {
  background: #0c0;
}
.b__b--3osya {
  color: #bbb;
}
```

As you can see, the results composed from app.css is included in all three bundles. Is there a way to combine this common code?

[Full working example here](https://github.com/mgreystone/demo-css-module-dynamic-import)

* node 8.9.1
* webpack 3.10.0
* extract-css-chunks-webpack-plugin 2.0.18
* flush-css-chunks-webpack-plugin 0.1.0
